language: ruby
before_install:
  - gem install bundler
rvm:
  - ruby-head
  - 2.2.2
  - 2.1
  - 2.0
gemfile:
  - gemfiles/rails_3.gemfile
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
